
DROP TABLE IF EXISTS Sale_Item;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Sale;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Branch;
DROP TABLE IF EXISTS Publisher;
DROP TABLE IF EXISTS Genre;