SELECT * FROM Genre;
SELECT * FROM Publisher;
SELECT * FROM Branch;
SELECT * FROM Customer;
SELECT * FROM Employee;
SELECT * FROM Book;
SELECT * FROM Sale;
SELECT * FROM Inventory;
SELECT * FROM Sale_Item;